version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project

jobs:
  lift_infra: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Spin up backend
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
       

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - lift_infra:
          filters:
            branches:
              only:
                -main
   